name:                warduino
version:             0.1.0.0
github:              "wchresta/warduino"
license:             BSD3
author:              "Wanja Chresta"
maintainer:          "wanja.hs@chrummibei.ch"
copyright:           "2018, Wanja Chresta"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/wchresta/warduino#readme>

dependencies:
- base >= 4.7 && < 5
- haskino >= 0.6

library:
  source-dirs: lib

executables:
  blink:
    main:                Main.hs
    source-dirs:         blink
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -fplugin=System.Hardware.Haskino.ShallowDeepPlugin
    dependencies:
    - warduino

#tests:
#  warduino-test:
#    main:                Spec.hs
#    source-dirs:         test
#    ghc-options:
#    - -threaded
#    - -rtsopts
#    - -with-rtsopts=-N
#    dependencies:
#    - warduino
